### ISSUE TITLE
View Both Sensors in battery.yaml: # Batterie volt and # Battery %.

### ISSUE THREAD

**Issue by Copyrighter** [bruvv/LILYGO-T-Higrow-Esphome#24]
How can I have both Sensors enabled in battery.yaml: # Batterie volt and # Battery %.?
If I add both of them, I see following error:
`Pin 33 is used in multiple places.`
Each one separately is working.

**Comment by bruvv** [comment]
fixed https://github.com/bruvv/LILYGO-T-Higrow-Esphome/commit/5fe36fa56ec550fb31f84db49eec0bc1607d725e

**Comment by Copyrighter** [comment]
@bruvv 
is there any other solution than escaping?
is there option to see both % and V?

**Comment by bruvv** [comment]
not that I know of. Mine broke so I cannot test it at the moment :(

**Comment by Copyrighter** [comment]
@bruvv 
I found a working fix ( tested ).
change syntax to:
---
  - platform: adc
    pin:
      number: 33
      allow_other_uses: true
...
---

**Comment by bruvv** [comment]
nice found! I added it to the repo:)
