### ISSUE TITLE
Error ⚠️ Failed to download manifest

### ISSUE THREAD

**Issue by P1X3L8** [bruvv/LILYGO-T-Higrow-Esphome#8]
Using your "Connect" page/button to provision these I receive "Error - Failed to download manifest" after selecting a T-HiGrow COM port and then pressing "Connect".

I'm able to flash using USB COM via https://web.esphome.io/ without issue.

I tested this on four different units using Chrome and Edge with the same result.

**Comment by bruvv** [comment]
Fixed! Thanks for noticing
